import Head from 'next/head'
import Navbar from '../components/navbar'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from 'react-icons/ai'

export default function Home() {
  return (
    <>
      <Head>
        <title>Esteban Bedoya portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className=" min-h-screen">
          <Navbar />
          
        </section>
      </main>
    </>
  )
}
